"""initial_multitenant_schema

Revision ID: 338ffc125a28
Revises: 
Create Date: 2026-06-01 16:57:00.172892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338ffc125a28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('nombre_display', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('derivadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radiologo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(), server_default='#6b7280', nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['radiologo_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_derivadores_id'), 'derivadores', ['id'], unique=False)
    op.create_table('tipos_examen_custom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radiologo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['radiologo_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('radiologo_id', 'nombre')
    )
    op.create_index(op.f('ix_tipos_examen_custom_id'), 'tipos_examen_custom', ['id'], unique=False)
    op.create_table('honorarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('derivador_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('detalle_json', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['derivador_id'], ['derivadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derivador_id', 'periodo')
    )
    op.create_index(op.f('ix_honorarios_id'), 'honorarios', ['id'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radiologo_id', sa.Integer(), nullable=False),
    sa.Column('derivador_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['derivador_id'], ['derivadores.id'], ),
    sa.ForeignKeyConstraint(['radiologo_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_table('portal_magic_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('derivador_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['derivador_id'], ['derivadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_portal_magic_links_id'), 'portal_magic_links', ['id'], unique=False)
    op.create_table('tarifas_derivador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('derivador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_examen', sa.String(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['derivador_id'], ['derivadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('derivador_id', 'tipo_examen')
    )
    op.create_index(op.f('ix_tarifas_derivador_id'), 'tarifas_derivador', ['id'], unique=False)
    op.create_table('examenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('derivador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_examen', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='0', nullable=True),
    sa.Column('notificacion_doctora_enviada', sa.Boolean(), nullable=True),
    sa.Column('notificacion_derivador_enviada', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('completado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['derivador_id'], ['derivadores.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examenes_id'), 'examenes', ['id'], unique=False)
    op.create_table('imagenes_examen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('ruta', sa.String(), nullable=False),
    sa.Column('subido_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagenes_examen_id'), 'imagenes_examen', ['id'], unique=False)
    op.create_table('incidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('comentario_doctora', sa.Text(), nullable=False),
    sa.Column('comentario_derivador', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('resuelto_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examen_id')
    )
    op.create_index(op.f('ix_incidencias_id'), 'incidencias', ['id'], unique=False)
    op.create_table('informes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('ruta_pdf', sa.String(), nullable=False),
    sa.Column('token_publico', sa.String(), nullable=False),
    sa.Column('subido_en', sa.DateTime(), nullable=True),
    sa.Column('notificacion_enviada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examen_id'),
    sa.UniqueConstraint('token_publico')
    )
    op.create_index(op.f('ix_informes_id'), 'informes', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radiologo_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('derivador_id', sa.Integer(), nullable=True),
    sa.Column('examen_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['derivador_id'], ['derivadores.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.ForeignKeyConstraint(['radiologo_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_table('revisiones_examen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('numero_version', sa.Integer(), nullable=False),
    sa.Column('tipo_cambio', sa.String(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisiones_examen_id'), 'revisiones_examen', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revisiones_examen_id'), table_name='revisiones_examen')
    op.drop_table('revisiones_examen')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_informes_id'), table_name='informes')
    op.drop_table('informes')
    op.drop_index(op.f('ix_incidencias_id'), table_name='incidencias')
    op.drop_table('incidencias')
    op.drop_index(op.f('ix_imagenes_examen_id'), table_name='imagenes_examen')
    op.drop_table('imagenes_examen')
    op.drop_index(op.f('ix_examenes_id'), table_name='examenes')
    op.drop_table('examenes')
    op.drop_index(op.f('ix_tarifas_derivador_id'), table_name='tarifas_derivador')
    op.drop_table('tarifas_derivador')
    op.drop_index(op.f('ix_portal_magic_links_id'), table_name='portal_magic_links')
    op.drop_table('portal_magic_links')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_honorarios_id'), table_name='honorarios')
    op.drop_table('honorarios')
    op.drop_index(op.f('ix_tipos_examen_custom_id'), table_name='tipos_examen_custom')
    op.drop_table('tipos_examen_custom')
    op.drop_index(op.f('ix_derivadores_id'), table_name='derivadores')
    op.drop_table('derivadores')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
