"""add_categoria_to_tipos_examen_custom

Revision ID: 953371e62acc
Revises: 338ffc125a28
Create Date: 2026-06-02 20:12:16.402366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953371e62acc'
down_revision: Union[str, Sequence[str], None] = '338ffc125a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_examen_custom', sa.Column('categoria', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_examen_custom', 'categoria')
    # ### end Alembic commands ###
